### PR TITLE
R-Pi shield and sensor board schematics and PCBs.

### PR DESCRIPTION
**Pull request by gunturiCM**
## Main Changes

Schematics and PCB design files for R-Pi shield and sensor board.

This is how it will look like (this sketch is conceptual and not to scale):

image

## Associated Issues

- Addresses #57

### CODE REVIEW

**Review by boyle26 — APPROVED** [review]
I'm happy to proceed with these 3 boards, a BOM will need to be compiled to check if we need to order any further components for them.

**Review by alphaville — COMMENTED** [review]
@gunturiCM @boyle26 are we planning to use such headers?

image

If so, do we have enough space on the ESP board? See below:

image

**Review by alphaville — COMMENTED** [review]
What is this?

image

**Comment by boyle26** [comment]
The mounting holes of the ESP and RPi board line up in both directions so we can have the USB on the same or opposite side. With regard to what you said about the RPi's and ESP's power supply, you are correct.

**Review by alphaville — APPROVED** [review]

**Comment by alphaville** [comment]
@gunturiCM @boyle26 one last thing: it would be good to collect the above images in a README file somewhere

**Pull request merged**
