### PR TITLE
Safety instructions (SAFETY.md)

### PR DESCRIPTION
**Pull request by alphaville**
## Main Changes

`SAFETY.md` is introduced: a document that attempts to identify the key hazards in the lab (e.g., soldering, handling LiPo batteries, and working with quadcopter motors) and propose a number of safety measures.

### CODE REVIEW

**Comment by alphaville** [comment]
@jamie-54 @gunturiCM: reminder

**Comment by jamie-54** [comment]
I'm happy with it

**Comment by gunturiCM** [comment]
Please look into these.
1. In section 5.1, Voltage deviation, typo in 5mV ~ 10Mv, which should be 5mV ~ 10mV.
2. In section 6.2, point 4, typo: "pinning propellers".
3. What does esp mean in section 9, point 2, sub-point 1? Is that a typo?

**Review by gunturiCM — APPROVED** [review]
Everything looks good.

**Pull request merged**
