### PR TITLE
Implementation of fail-safes

### LINKED ISSUE #29: Fail safes
Implement the following safety measures (these are common safety measure I've found online):

- [x] **Arm switch:** the motors will not arm unless the arm switch is flipped
- [x] **Kill switch:** the kill switch kills the motors
- [x] **Buzzer:** the buzzer makes a sound before arming (or re-arming) and after disarming
- [x] **Lost connection:** they say that if the copter looses connection, it should shutdown immediately

### PR DESCRIPTION
**Pull request by alphaville**
## Main Changes

- check arming switch in setup
- check kill switch in loop
- disarm and exit loop if killed

## TODOs

- [x] 1. use buzzer

Note: We also need to kill when there is no signal from the radio (perhaps in a different PR)

## Associated Issues

- Addresses #29

### CODE REVIEW

**Comment by jamie-54** [comment]
This set up means we have to rest the ESP32 whenever the kill switch is triggered, previously the readKillSwitch function was implemented that allowed the receiver signals to be read but only returned the kill switch channel, this meant if the the switch was then turned off we could control the quadrotor again. Do we want to add this function again?

**Comment by alphaville** [comment]
> This set up means we have to rest the ESP32 whenever the kill switch is triggered, previously the readKillSwitch function was implemented that allowed the receiver signals to be read but only returned the kill switch channel, this meant if the the switch was then turned off we could control the quadrotor again. Do we want to add this function again?

I see that `readKillSwitch` returned a `float`, whereas `radioKill` returns a `bool`. Is there a reason why we might need the value of `channelData[RADIO_CHANNEL_SWITCH_A]` as a `float`? It seems to me that `radioKill` provides the same information, isn't it?

**Comment by jamie-54** [comment]
> > This set up means we have to rest the ESP32 whenever the kill switch is triggered, previously the readKillSwitch function was implemented that allowed the receiver signals to be read but only returned the kill switch channel, this meant if the the switch was then turned off we could control the quadrotor again. Do we want to add this function again?
> 
> I see that `readKillSwitch` returned a `float`, whereas `radioKill` returns a `bool`. Is there a reason why we might need the value of `channelData[RADIO_CHANNEL_SWITCH_A]` as a `float`? It seems to me that `radioKill` provides the same information, isn't it?

whenever the kill switch is triggered we still want to be able to read the receiver signals to see if the kill switch has been turned off again. If we use the `readPiData` function that means the other signal can still be read and the quadcopter will behave as if the switch hasn’t been turned on. By using the `readKillSwitch` function we can still read the signal for the kill switch without reading any of the other signals. This means that when the kill switch is then turned on again we have control over the quadcopter again. Hopefully that makes sense?

**Comment by alphaville** [comment]
Hmm, sorry, I still don't get it. This is `kill`:

```c++
bool Radio::kill() {
    return channelData[RADIO_CHANNEL_SWITCH_A] >= 1500;
}
```

and this is `readKillSwitch`:

```c++
float Radio::readKillSwitch() {
   return channelData[RADIO_CHANNEL_SWITCH_A];
}
```

They provide the same information, isn't it?

**Comment by jamie-54** [comment]
> Hmm, sorry, I still don't get it. This is `kill`:
> 
> ```c++
> bool Radio::kill() {
>     return channelData[RADIO_CHANNEL_SWITCH_A] >= 1500;
> }
> ```
> 
> and this is `readKillSwitch`:
> 
> ```c++
> float Radio::readKillSwitch() {
>    return channelData[RADIO_CHANNEL_SWITCH_A];
> }
> ```
> 
> They provide the same information, isn't it?

The `readKillSwitch` function should be like this

 ```c++
    float Radio::readKillSwitch()
    {
        Radio::readPiData();
         return channelData[RADIO_CHANNEL_SWITCH_A];
    }
 ```

This means the function reads the pi data but only returns the kill switch signal.

Then if we include the following code in the `main.cpp` file we can just read the kill switch signal when the kill switch is on so that when it is switched of we can return back to the rest of the code and start controlling the quadcopter again. 

 ```c++
  if (radio.kill()) 
    {
      //Disarm motors then check if if kill switch is on or off
      motorDriver.disarm();
      while(radio.kill())
      {
        radio.readKillSwitch();
      }
    }
 ```

**Comment by alphaville** [comment]
@jamie-54 you're right! I'll update it.

**Comment by jamie-54** [comment]
> @jamie-54 you're right! I'll update it.

No problem sorry it was hard to explain

**Comment by alphaville** [comment]
@jamie-54 Have a look now. In principle I'm not in favour of `readKillSwitch` because it breaks the pattern (all other methods don't call `readPiData`; besides `readPiData` is a separate method to control when to read the data from the serial). 

I've also re-introduced some changes that seem to have been lost (e.g., I removed `readRadioData` and changed `readPiData` to return `bool`).

**Comment by jamie-54** [comment]
> @jamie-54 Have a look now. In principle I'm not in favour of `readKillSwitch` because it breaks the pattern (all other methods don't call `readPiData`; besides `readPiData` is a separate method to control when to read the data from the serial).
> 
> I've also re-introduced some changes that seem to have been lost (e.g., I removed `readRadioData` and changed `readPiData` to return `bool`).

We don't have to use `readKillSwitch` if anyone has any other suggestions but I couldn't think of any other way for telling when the switch is turned of again.

**Comment by alphaville** [comment]
What do you think about the current version (check out what I pushed earlier today?

**Comment by jamie-54** [comment]
I'll test it on the hardware thanks

**Comment by jamie-54** [comment]
This isn't working and I'm not sure what's wrong.
 The `waitForArmCommand` doesn't seen to be working properly as the motors arm straight away after `buzz` function.
Also should the  `waitForArmCommand` function not have the `readPiData` inside the while loop otherwise how will it know when the arm switch triggered?

**Comment by alphaville** [comment]
@jamie-54 I'm not sure what's wrong. Can you try the following instead?

```c++
void waitForArmCommand()
{
  radio.readPiData();
  while (!radio.armed())
  {
    radio.readPiData();
  }
}
```

**Review by jamie-54 — APPROVED** [review]
I'm happy to merge if you are?

**Pull request merged**
