### PR TITLE
New contributing guidelines

### PR DESCRIPTION
**Pull request by alphaville**
# Description

First version of `contributing.md`: 

- Working with git (branches, PRs, issues, etc)
- Good coding practice and naming conventions in C++ and Python
- Project structure
- Documentation
- Unit testing

[View the file](https://github.com/QUB-ASL/bzzz/blob/feature/contributing/CONTRIBUTING.md)

### CODE REVIEW

**Review by jamie-54 — APPROVED** [review]
Thank you for the detailed contributing guidelines.

**Comment by alphaville** [comment]
@jamie-54 I made some final changes ([see here](https://github.com/QUB-ASL/bzzz/pull/1/commits/b75792691616bd1260104361c90a1e01874c1bf6)). If you're happy with these we can merge this PR.

**Review by jamie-54 — APPROVED** [review]
Happy with changes thanks!

**Review by jamie-54 — APPROVED** [review]
Happy with changes!

**Pull request merged**
